config/routes.rb
Lifecare::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  match '/update' => 'home#update', :as => :update
  match '/features' => 'home#features', :as => :features
  match '/mine' => 'home#mine', :as => :mine	

  # different uploaded versions
  match '/uploads/grid/user/avatar/:id/:filename' => 'gridfs#thumb_avatar', constraints: { filename: /thumb.*/ }
  # route configuration for the uploaded image
  match '/uploads/grid/user/avatar/:id/:filename' => 'gridfs#avatar'

  # different uploaded versions
  match '/uploads/grid/redactor_rails/picture/data/:id/:filename' => 'gridfs#thumb_redactor_pitcure', constraints: { filename: /thumb.*/ }
  # route configuration for the uploaded image
  match '/uploads/grid/redactor_rails/picture/data/:id/:filename' => 'gridfs#redactor_pitcure'
  

  scope 'communities' do
    match '/:community_id/columns/:id' => 'widgets/columns#show', :as => :show_community_column, :via => :get
    match '/:community_id/articles/:id' => 'widgets/articles#show', :as => :show_community_article, :via => :get
    match '/:community_id/articles/:id/comment' => 'widgets/articles#comment', :as => :comment_community_article, :via => :get  

    match '/:community_id/forum/:id' => 'widgets/forums#show', :as => :show_community_forum, :via => :get
    match '/:community_id/topics/:id' => 'widgets/topics#show', :as => :show_community_topic, :via => :get
    match '/:community_id/topics/:id/comment' => 'widgets/topics#comment', :as => :comment_community_topic, :via => :get

    match '/:community_id/qas/:id' => 'widgets/qas#show', :as => :show_community_qa, :via => :get
    match '/:community_id/questions/:id' => 'widgets/questions#show', :as => :show_community_question, :via => :get

    match '/:community_id/poll_sets/:id' => 'widgets/poll_sets#show', :as => :show_community_poll_set, :via => :get
    match '/:community_id/polls/:id' => 'widgets/polls#show', :as => :show_community_poll, :via => :get
    match '/:community_id/polls/:id/comment' => 'widgets/polls#comment', :as => :comment_community_poll, :via => :get
  end    

  resources :blogs do 
  	get 'comment', :on => :member
  end  

  resources :communities do
    resources :sections

    scope :module => "widgets" do
      resources :bulletins, only: [:edit, :update]
      resources :forums, :only => :update do
        resources :topics, except: :show
      end  
      resources :poll_sets, :only => :update do
        resources :polls, except: :show
      end 
      resources :qas, :only => :update do
        resources :questions, except: :show
      end  
      resources :columns, :only => :update do
        resources :articles, except: :show
      end

      resources :video_lists, :only => :update do
        resources :videos, except: :show
      end
    end

    get 'admin', :on => :member
    get 'join', :on => :member
    get 'leave', :on => :member
  end

  resources :phrs do
    scope :module => "phrs" do
      resources :conditions
      resources :symptoms
      resources :treatments
    end

    # get 'conditions', :on => :member
    # get 'symptoms', :on => :member
    # get 'treatments', :on => :member
  end

  authenticated :user do
    root :to => 'home#update'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
    get :avatar, on: :member
  end

  resource :feature_filter
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :communities]

  has_widgets do |root|    
    root << widget(:update_list) 
  end

  def index
    @users = User.all
  end

  def update
  end
  
  def features
    @feature_filter = current_user.feature_filter
    @keywords = current_user.feature_filter.merged_keywords

    if params[:category]
      if @keywords.nil? or @keywords.empty?
        @items = Content.where(category: params[:category])
      else
        @items = Content.where(category: params[:category]).full_text_search(@keywords)
      end  
    else
      if @keywords.nil? or @keywords.empty?
        @items = Content.all
      else
        @items = Content.all.full_text_search(@keywords)
      end 
    end 
  end

  def mine
    if params[:phr]
      @phr = Phr.find params[:phr]
    else
      @phr = current_user.phrs.first
    end
    @condition = @phr.conditions.build
    @symptom = @phr.symptoms.build
    @treatment = @phr.treatments.build
  end	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/features.html.haml
%h3 Features
%ul.nav
  %li{:class => "#{params[:category].nil?? 'current' : nil }"} 
    = link_to '所有', features_path
  %li{:class => "#{params[:category] == '健康知识'? 'current' : nil }"} 
    = link_to '健康知识', features_path(:category => '健康知识')
  %li{:class => "#{params[:category] == '就医指南'? 'current' : nil }"} 
    = link_to '就医指南', features_path(:category => '就医指南')
  %li{:class => "#{params[:category] == '治疗交流'? 'current' : nil }"}  
    = link_to '治疗交流', features_path(:category => '治疗交流')
  %li{:class => "#{params[:category] == '护理园地'? 'current' : nil }"} 
    = link_to '护理园地', features_path(:category => '护理园地') 
  %li{:class => "#{params[:category] == '用药常识'? 'current' : nil }"}  
    = link_to '用药常识', features_path(:category => '用药常识')          

%h4 
  精选内容
  %small 
    %a.link-setting{:href => "#"} 设置
.features-setting
  = form_for @feature_filter, :url => feature_filter_url do |f|
    %p 显示与您和家人健康相关的内容
    %p 
      %small 相关疾病
    - @feature_filter.conditions.each do |k, v|
      = f.fields_for :conditions do |c|
        = c.check_box k, checked: (v == "1" ? "checked" : "")
        %small
          = c.label k
    %p 
      %small 相关病症
    - @feature_filter.symptoms.each do |k, v|
      = f.fields_for :symptoms do |c|
        = c.check_box k, checked: (v == "1" ? "checked" : "") 
        %small
          = c.label k     
    %p    
      = f.submit '保存'

%ul
- @items.each do |item|
  %li
    - if item.class.to_s.underscore == 'blog'
      = link_to item.title, blog_url(item)
    - else
      = link_to item.title, self.send("show_community_#{item.class.to_s.underscore}_url", item.community, item)
    %br
    %small #{time_ago_in_words(item.created_at).capitalize}前 #{item.category}
    %br
    %small
      / - if item.liked?(current_user)
      /   %a{:href => "#"} 取消收藏
      / - else  
      /   %a{:href => "#"} 收藏

:javascript
  $(document).ready(function(){
    $('.features-setting').hide();
      $('.link-setting').click(function() {
        $('.features-setting').slideToggle();
    });
  });        

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/home/mine.html.haml
- @blog = Blog.new

%h3 我的健康
%h4 我的日志
= link_to '写日记', new_blog_path
%ul
  - current_user.blogs.each do |blog|
    %li
      = link_to blog.title, blog_path(blog)
%h4 我的健康记录    
#{@phr.name} #{@phr.age}
= link_to '添加健康记录', new_phr_path
%a.switch-phr{:href => "#"} 切换健康记录
.phrs
  %ul
  - current_user.phrs.excludes(:id => @phr.id).each do |p|
    %li 
      #{link_to p.name, mine_path(:phr => p)}

%hr
= link_to '疾病', phr_conditions_path(@phr)
%a.condition-link{:href => "#", "data-reveal-id" => 'myCondition'} 添加
%br
- @phr.conditions.each do |c|
  #{c.name} 
%p
  = link_to '病症', phr_symptoms_path(@phr)
  %a.symptom-link{:href => "#", "data-reveal-id" => 'mySymptom'} 添加
  %br
  - @phr.symptoms.each do |c|
    #{c.name}   
%p
  = link_to '治疗', phr_treatments_path(@phr)
  %a.treatment-link{:href => "#", "data-reveal-id" => 'myTreatment'} 添加
  %br
  - @phr.treatments.each do |c|
    #{c.name}   

%h4 我的收藏


.reveal-modal#myCondition
  %h2 添加疾病
  = form_for :condition, :url => phr_conditions_path(@phr) do |f|
    %p
      = f.label "名称"
      = f.text_field :name
    %p
      = f.label "状态"
      = f.text_field :status
    %p  
      = f.submit "保存"   
  %a.close-reveal-modal &#215;

.reveal-modal#mySymptom
  %h2 添加病症
  = form_for :symptom, :url => phr_symptoms_path(@phr) do |f|
    %p
      = f.label "名称"
      = f.text_field :name
    %p
      = f.label "程度"
      = f.text_field :extent
    %p  
      = f.submit "保存"   
  %a.close-reveal-modal &#215;

.reveal-modal#myTreatment
  %h2 添加治疗
  = form_for :treatment, :url => phr_treatments_path(@phr) do |f|
    %p
      = f.label "名称"
      = f.text_field :name
    %p
      = f.label "剂量"
      = f.text_field :dose
    %p  
      = f.submit "保存"   
  %a.close-reveal-modal &#215;    

  :javascript 
    $(document).ready(function() {
      $('.condition-link').click(function(e) {
        e.preventDefault();
        $('#myCondition').reveal();
      });

      $('.symptom-link').click(function(e) {
        e.preventDefault();
        $('#mySymptom').reveal();
      });

      $('.treatment-link').click(function(e) {
        e.preventDefault();
        $('#myTreatment').reveal();
      });

      $('.phrs').hide();
      $('.switch-phr').click(function() {
        $('.phrs').slideToggle();
      });
    });  

app/views/home/update.html.haml
%h3 My Communities Update
= render_widget :update_list
/ - @activities.each do |activity|
/   .activity-feed
/     - present activity, ActivityPresenter do |activity_presenter|
/       .metadata
/         %p
/           #{activity_presenter.metadata}
/         %p
/           #{activity_presenter.text } 
/         - if activity_presenter.content?
/           .content
/             #{activity.the_object.body}

/ = paginate @activities, :remote => true